In [1]:
#Goal: use the google trends API to get google search data on Glossier and Glossier competitors 
#source used: https://towardsdatascience.com/a-very-precise-fast-way-to-pull-google-trends-data-automatically-4c3c431960aa
#credit for this script goes to the source in the above link! 
pip install pytrends

Collecting pytrends
  Downloading pytrends-4.8.0.tar.gz (19 kB)
Requirement already satisfied: requests>=2.0 in /opt/anaconda3/lib/python3.8/site-packages (from pytrends) (2.25.1)
Requirement already satisfied: pandas>=0.25 in /opt/anaconda3/lib/python3.8/site-packages (from pytrends) (1.2.4)
Requirement already satisfied: lxml in /opt/anaconda3/lib/python3.8/site-packages (from pytrends) (4.6.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.25->pytrends) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.25->pytrends) (2021.1)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.25->pytrends) (1.20.1)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas>=0.25->pytrends) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.0->pytrends) (2022.6.15)
Requirement already satisfied: chardet<5,>=3.0.2 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.0->pytrends) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.0->pytrends) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.0->pytrends) (1.26.4)
Building wheels for collected packages: pytrends
  Building wheel for pytrends (setup.py) ... done
  Created wheel for pytrends: filename=pytrends-4.8.0-py3-none-any.whl size=16105 sha256=6de9eaac0c614831d01492f15d4a1b7bd3fb28b01ab21be443e65bd3fbafd8f3
  Stored in directory: /Users/astahl/Library/Caches/pip/wheels/e8/78/c8/18d4f4804753e14416809b365773220c48b41fe5387f2bb6b9
Successfully built pytrends
Installing collected packages: pytrends
Successfully installed pytrends-4.8.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
#Data Gathering

In [5]:
import pandas as pd
import pytrends
from pytrends.request import TrendReq
pytrend = TrendReq()

In [8]:
#google automatically includes upper and lower case variations so I dont need to worry about that 
makeup=['Sephora','Ulta','Fenty','Glossier'] 
makeup_n=[pytrend.suggestions(keyword=i)[0] for i in makeup] 
df_makeup= pd.DataFrame(makeup_n)
df_makeup

             mid           title    type
0      /m/05nn45         Sephora  Retail
1     /m/03p3r21     Ulta Beauty   Topic
2  /g/11h84w61q8  SAVAGE X FENTY   Topic
3  /g/11h_cd2125        Glossier   Topic

In [10]:
#Now we can use the exact codes to pull the data 
mid=df_makeup['mid'].to_list()
#set time frame to same as reddit data 
#the google API is a little tricky so I am going to do this multiple times and then concat the dataframes 
#the reason for this is that if you make the time period tow beeg it gives you data on a weekly basis instead of daily 
#we want as muhc data as possible so daily is best 
DATE_INTERVAL_1='2021-01-01 2021-09-01'
DATE_INTERVAL_2='2021-09-02 2022-05-01'
DATE_INTERVAL_3='2022-05-02 2022-08-31'
CATEGORY=0 
SEARCH_TYPE=''

In [11]:
Individual_EXACT_KEYWORD = list(zip(*[iter(EXACT_KEYWORDS)]*1))
Individual_EXACT_KEYWORD = [list(x) for x in Individual_EXACT_KEYWORD]
dicti = {}
i = 1

for keyword in Individual_EXACT_KEYWORD:
        pytrend.build_payload(kw_list=keyword, 
                                timeframe = DATE_INTERVAL_1, 
                                cat=CATEGORY,
                                gprop=SEARCH_TYPE) 
        dicti[i] = pytrend.interest_over_time()
        i+=1
df_trends1 = pd.concat(dicti, axis=1)

ResponseError: The request failed: Google returned a response with code 429.

In [109]:
Individual_EXACT_KEYWORD = list(zip(*[iter(EXACT_KEYWORDS)]*1))
Individual_EXACT_KEYWORD = [list(x) for x in Individual_EXACT_KEYWORD]
dicti = {}
i = 1

for keyword in Individual_EXACT_KEYWORD:
        pytrend.build_payload(kw_list=keyword, 
                                timeframe = DATE_INTERVAL_2, 
                                cat=CATEGORY,
                                gprop=SEARCH_TYPE) 
        dicti[i] = pytrend.interest_over_time()
        i+=1
df_trends2 = pd.concat(dicti, axis=1)

In [110]:
Individual_EXACT_KEYWORD = list(zip(*[iter(EXACT_KEYWORDS)]*1))
Individual_EXACT_KEYWORD = [list(x) for x in Individual_EXACT_KEYWORD]
dicti = {}
i = 1

for keyword in Individual_EXACT_KEYWORD:
        pytrend.build_payload(kw_list=keyword, 
                                timeframe = DATE_INTERVAL_3, 
                                cat=CATEGORY,
                                gprop=SEARCH_TYPE) 
        dicti[i] = pytrend.interest_over_time()
        i+=1
df_trends3 = pd.concat(dicti, axis=1)

In [111]:
df_trends1.columns = df_trends1.columns.droplevel(0) 
df_trends1 = df_trends1.drop('isPartial', axis = 1) 
df_trends1.reset_index(level=0,inplace=True) 
df_trends1.columns=['Date','Sephora','Ulta','Fenty','Glossier'] 
df_trends1

          Date  Sephora  Ulta  Fenty  Glossier
0   2021-01-01       88   100     70        35
1   2021-01-02       97    96    100        41
2   2021-01-03      100    96     84        44
3   2021-01-04       85    74     72        32
4   2021-01-05       84    70     58        35
..         ...      ...   ...    ...       ...
239 2021-08-28       66    72     26        19
240 2021-08-29       70    74     26        24
241 2021-08-30       64    53     22        21
242 2021-08-31       65    56     25        25
243 2021-09-01       71    65     77        23

[244 rows x 5 columns]

In [112]:
df_trends2.columns = df_trends2.columns.droplevel(0) 
df_trends2 = df_trends2.drop('isPartial', axis = 1) 
df_trends2.reset_index(level=0,inplace=True) 
df_trends2.columns=['Date','Sephora','Ulta','Fenty','Glossier'] 
df_trends2

          Date  Sephora  Ulta  Fenty  Glossier
0   2021-09-02       28    29     57        15
1   2021-09-03       29    31     52        15
2   2021-09-04       31    36     48        16
3   2021-09-05       30    33     58        20
4   2021-09-06       28    33     49        23
..         ...      ...   ...    ...       ...
237 2022-04-27       31    26     15        22
238 2022-04-28       30    28     14        24
239 2022-04-29       34    32     16        30
240 2022-04-30       34    33     18        29
241 2022-05-01       34    33     42        28

[242 rows x 5 columns]

In [113]:
df_trends3.columns = df_trends3.columns.droplevel(0) 
df_trends3 = df_trends3.drop('isPartial', axis = 1) 
df_trends3.reset_index(level=0,inplace=True) 
df_trends3.columns=['Date','Sephora','Ulta','Fenty','Glossier'] 
df_trends3

          Date  Sephora  Ulta  Fenty  Glossier
0   2022-05-02       93   100     77        33
1   2022-05-03       86    87     63        43
2   2022-05-04       89    68     58        33
3   2022-05-05       86    67     63        32
4   2022-05-06       96    77     41        29
..         ...      ...   ...    ...       ...
117 2022-08-27       95    78     33        43
118 2022-08-28       93    90     24        38
119 2022-08-29       88    67     24        41
120 2022-08-30       95    65     33        36
121 2022-08-31       88    67     30        33

[122 rows x 5 columns]

In [116]:
#now We need to put the two datasets together 
df_trends=pd.concat([df_trends1, df_trends2, df_trends3])
df_trends
df_trends
#save to csv 
df_trends.to_csv('google_trends_competitors.csv',index=False)